import type { JubenshaScript, JubenshaRole, JubenshaClue } from './types.js';

// 示例剧本数据 - 基于 the-one-truth 项目的数据结构
interface ScriptWithDetails extends JubenshaScript {
  roles: JubenshaRole[];
  clues: JubenshaClue[];
}

export const DEMO_SCRIPTS: ScriptWithDetails[] = [
  {
    scriptId: 'script_lihua_hotel',
    title: '梨花旅店',
    description: '一个发生在古风旅店的悬疑故事，六位旅客各怀心事，一场命案打破了夜的宁静...',
    playerNum: 6,
    truth: '店主李梨花因发现丈夫出轨，在争执中失手杀人',
    murderId: 'role_lihua_1',
    addTime: new Date().toISOString(),
    roles: [
      {
        roleId: 'role_lihua_1',
        roleName: '李梨花',
        scriptId: 'script_lihua_hotel',
        roleScriptId: 0,
        isMurder: true,
        task: '隐藏自己的罪行，将嫌疑引向他人',
        background: '梨花旅店的女店主，温婉贤淑，与丈夫经营这家旅店已有十年。最近发现丈夫与一位女客人有染，内心痛苦不已。',
        timeline: '傍晚：在厨房准备晚餐\n入夜：与丈夫发生争执\n深夜：独自在房间哭泣',
        roleDescription: '30岁，旅店女主人，外表柔弱但内心坚强',
      },
      {
        roleId: 'role_lihua_2',
        roleName: '张书生',
        scriptId: 'script_lihua_hotel',
        roleScriptId: 1,
        isMurder: false,
        task: '找出真凶，还自己清白',
        background: '进京赶考的书生，因盘缠不足暂住此店。为人正直，但因与死者有过争执而成为嫌疑人。',
        timeline: '傍晚：在房间温书\n入夜：听到争吵声\n深夜：被惊醒，发现命案',
        roleDescription: '22岁，书生，清瘦文弱，戴着眼镜',
      },
      {
        roleId: 'role_lihua_3',
        roleName: '王镖师',
        scriptId: 'script_lihua_hotel',
        roleScriptId: 2,
        isMurder: false,
        task: '保护好自己押送的货物，协助查案',
        background: '押镖途经此地的镖师，武艺高强，为人豪爽。身上带着一批贵重货物，警惕性很高。',
        timeline: '傍晚：检查货物\n入夜：在大堂喝酒\n深夜：巡视旅店',
        roleDescription: '35岁，镖师，身材魁梧，面带刀疤',
      },
      {
        roleId: 'role_lihua_4',
        roleName: '柳如烟',
        scriptId: 'script_lihua_hotel',
        roleScriptId: 3,
        isMurder: false,
        task: '隐藏自己与死者的关系',
        background: '神秘的女旅客，自称是去投奔亲戚。实际上是与店主丈夫有染的女子，此行是来私奔的。',
        timeline: '傍晚：在房间梳妆\n入夜：与某人密会\n深夜：躲在房间不敢出门',
        roleDescription: '25岁，神秘女子，容貌姣好，举止优雅',
      },
      {
        roleId: 'role_lihua_5',
        roleName: '老道士',
        scriptId: 'script_lihua_hotel',
        roleScriptId: 4,
        isMurder: false,
        task: '找出真相，超度亡魂',
        background: '云游四方的道士，自称能通阴阳。实际上是个骗子，但这次似乎真的感应到了什么。',
        timeline: '傍晚：在院中打坐\n入夜：突然惊醒，说感应到凶兆\n深夜：四处查看',
        roleDescription: '50岁，道士，仙风道骨，手持拂尘',
      },
      {
        roleId: 'role_lihua_6',
        roleName: '小二',
        scriptId: 'script_lihua_hotel',
        roleScriptId: 5,
        isMurder: false,
        task: '回忆当晚看到的一切，提供线索',
        background: '旅店的伙计，在这里工作三年了。对旅店的一切了如指掌，当晚看到了一些不寻常的事情。',
        timeline: '傍晚：招待客人\n入夜：打扫卫生\n深夜：在柴房休息',
        roleDescription: '18岁，店小二，机灵活泼，消息灵通',
      },
    ],
    clues: [
      {
        clueId: 'clue_lihua_1',
        scriptId: 'script_lihua_hotel',
        roleId: 'role_lihua_1',
        clueScriptId: 0,
        text: '血迹',
        clueDescription: '在厨房角落发现了一小滩血迹，似乎有人试图清理过',
      },
      {
        clueId: 'clue_lihua_2',
        scriptId: 'script_lihua_hotel',
        roleId: 'role_lihua_2',
        clueScriptId: 1,
        text: '情书',
        clueDescription: '一封写给柳如烟的情书，署名是店主的丈夫',
      },
      {
        clueId: 'clue_lihua_3',
        scriptId: 'script_lihua_hotel',
        roleId: 'role_lihua_3',
        clueScriptId: 2,
        text: '脚印',
        clueDescription: '在后院发现了一串女子的脚印，通向柴房',
      },
      {
        clueId: 'clue_lihua_4',
        scriptId: 'script_lihua_hotel',
        roleId: 'role_lihua_4',
        clueScriptId: 3,
        text: '首饰',
        clueDescription: '一只精美的耳环，与柳如烟佩戴的是一对',
      },
      {
        clueId: 'clue_lihua_5',
        scriptId: 'script_lihua_hotel',
        roleId: 'role_lihua_5',
        clueScriptId: 4,
        text: '凶器',
        clueDescription: '一把沾血的菜刀，藏在厨房的柴堆下',
      },
      {
        clueId: 'clue_lihua_6',
        scriptId: 'script_lihua_hotel',
        roleId: 'role_lihua_6',
        clueScriptId: 5,
        text: '证词',
        clueDescription: '小二说当晚看到店主夫妇在厨房激烈争吵',
      },
    ],
  },
  {
    scriptId: 'script_general_letter',
    title: '巴顿将军的信',
    description: '二战末期，一封神秘的信件引发了一场致命的阴谋。五位军官各怀鬼胎，谁才是真正的叛徒？',
    playerNum: 5,
    truth: '情报官汉斯是德国间谍，为了获取信件内容杀害了将军的副官',
    murderId: 'role_general_3',
    addTime: new Date().toISOString(),
    roles: [
      {
        roleId: 'role_general_1',
        roleName: '约翰上校',
        scriptId: 'script_general_letter',
        roleScriptId: 0,
        isMurder: false,
        task: '找出叛徒，保护信件安全',
        background: '巴顿将军的心腹，负责保管那封重要的信件。为人正直，但最近压力很大。',
        timeline: '下午：与将军会面\n傍晚：在办公室处理文件\n夜间：发现副官被杀',
        roleDescription: '45岁，陆军上校，严肃正直，军功卓著',
      },
      {
        roleId: 'role_general_2',
        roleName: '玛丽护士',
        scriptId: 'script_general_letter',
        roleScriptId: 1,
        isMurder: false,
        task: '隐藏自己与副官的秘密关系',
        background: '军医院的护士长，与死去的副官有一段秘密恋情。当晚曾与副官见面。',
        timeline: '下午：在医院工作\n傍晚：与副官秘密约会\n夜间：回到宿舍',
        roleDescription: '28岁，护士长，温柔美丽，深受士兵爱戴',
      },
      {
        roleId: 'role_general_3',
        roleName: '汉斯情报官',
        scriptId: 'script_general_letter',
        roleScriptId: 2,
        isMurder: true,
        task: '销毁证据，嫁祸他人',
        background: '军队情报部门的官员，实际上是德国安插的间谍。为了获取信件内容，杀害了副官。',
        timeline: '下午：整理情报\n傍晚：跟踪副官\n夜间：实施谋杀',
        roleDescription: '35岁，情报官，沉默寡言，观察力敏锐',
      },
      {
        roleId: 'role_general_4',
        roleName: '威廉少校',
        scriptId: 'script_general_letter',
        roleScriptId: 3,
        isMurder: false,
        task: '证明自己的清白',
        background: '后勤部门的少校，因为与副官有过节而成为嫌疑人。实际上当晚在仓库盘点物资。',
        timeline: '下午：检查补给\n傍晚：在仓库工作\n夜间：被叫去问话',
        roleDescription: '40岁，后勤少校，精明能干，有些贪财',
      },
      {
        roleId: 'role_general_5',
        roleName: '彼得通讯兵',
        scriptId: 'script_general_letter',
        roleScriptId: 4,
        isMurder: false,
        task: '提供关键证词',
        background: '负责通讯的年轻士兵，当晚值班时截获了一段可疑的电报。',
        timeline: '下午：维护设备\n傍晚：值班\n夜间：截获可疑电报',
        roleDescription: '22岁，通讯兵，年轻机警，技术过硬',
      },
    ],
    clues: [
      {
        clueId: 'clue_general_1',
        scriptId: 'script_general_letter',
        roleId: 'role_general_1',
        clueScriptId: 0,
        text: '信件残片',
        clueDescription: '在壁炉中发现了被烧毁的信件残片，上面有德文字迹',
      },
      {
        clueId: 'clue_general_2',
        scriptId: 'script_general_letter',
        roleId: 'role_general_2',
        clueScriptId: 1,
        text: '情书',
        clueDescription: '玛丽写给副官的情书，约定当晚在仓库见面',
      },
      {
        clueId: 'clue_general_3',
        scriptId: 'script_general_letter',
        roleId: 'role_general_3',
        clueScriptId: 2,
        text: '密码本',
        clueDescription: '一本德军使用的密码本，藏在情报官的抽屉里',
      },
      {
        clueId: 'clue_general_4',
        scriptId: 'script_general_letter',
        roleId: 'role_general_4',
        clueScriptId: 3,
        text: '账本',
        clueDescription: '威廉少校的私人账本，记录了一些可疑的交易',
      },
      {
        clueId: 'clue_general_5',
        scriptId: 'script_general_letter',
        roleId: 'role_general_5',
        clueScriptId: 4,
        text: '电报记录',
        clueDescription: '一份发往柏林的加密电报，时间是案发前一小时',
      },
    ],
  },
  {
    scriptId: 'script_test_3p',
    title: '测试剧本（3人）',
    description: '一个简单的3人测试剧本，用于快速体验游戏流程',
    playerNum: 3,
    truth: '角色A是凶手',
    murderId: 'role_test_1',
    addTime: new Date().toISOString(),
    roles: [
      {
        roleId: 'role_test_1',
        roleName: '角色A',
        scriptId: 'script_test_3p',
        roleScriptId: 0,
        isMurder: true,
        task: '隐藏身份',
        background: '神秘人物A的背景故事',
        timeline: '时间线A',
        roleDescription: '角色A的描述',
      },
      {
        roleId: 'role_test_2',
        roleName: '角色B',
        scriptId: 'script_test_3p',
        roleScriptId: 1,
        isMurder: false,
        task: '找出凶手',
        background: '神秘人物B的背景故事',
        timeline: '时间线B',
        roleDescription: '角色B的描述',
      },
      {
        roleId: 'role_test_3',
        roleName: '角色C',
        scriptId: 'script_test_3p',
        roleScriptId: 2,
        isMurder: false,
        task: '找出凶手',
        background: '神秘人物C的背景故事',
        timeline: '时间线C',
        roleDescription: '角色C的描述',
      },
    ],
    clues: [
      {
        clueId: 'clue_test_1',
        scriptId: 'script_test_3p',
        roleId: 'role_test_1',
        clueScriptId: 0,
        text: '线索1',
        clueDescription: '这是角色A的线索，指向凶手',
      },
      {
        clueId: 'clue_test_2',
        scriptId: 'script_test_3p',
        roleId: 'role_test_2',
        clueScriptId: 1,
        text: '线索2',
        clueDescription: '这是角色B的线索',
      },
      {
        clueId: 'clue_test_3',
        scriptId: 'script_test_3p',
        roleId: 'role_test_3',
        clueScriptId: 2,
        text: '线索3',
        clueDescription: '这是角色C的线索',
      },
    ],
  },
];

export function getScriptById(scriptId: string): ScriptWithDetails | undefined {
  return DEMO_SCRIPTS.find(s => s.scriptId === scriptId);
}

export function getScriptsByPlayerNum(playerNum: number): ScriptWithDetails[] {
  return DEMO_SCRIPTS.filter(s => s.playerNum === playerNum);
}
