/**
 * Metadata Extractor
 * 
 * Extracts script metadata from folder names including title, player count,
 * category, and difficulty.
 */

import type { ScriptMetadata } from './types';

/**
 * Extract the script title from a folder name.
 * Removes common prefixes like numbers and special characters.
 * 
 * Examples:
 * - "367-第二十二条校规（7人开放）" -> "第二十二条校规"
 * - "5210 K系列-觉醒" -> "K系列-觉醒"
 * - "病娇男孩的精分日记（无水印）" -> "病娇男孩的精分日记"
 */
export function extractTitleFromFolderName(folderName: string): string {
  let title = folderName;
  
  // Remove leading numbers and separators (e.g., "367-", "5210 ")
  title = title.replace(/^[\d]+[-\s]*/, '');
  
  // Remove player count patterns like "(7人开放)", "(4人)", "（7人）"
  title = title.replace(/[（(]\d+人[开放）)]*[）)]/g, '');
  
  // Remove watermark indicators like "(无水印)", "（无水印）"
  title = title.replace(/[（(]无水印[）)]/g, '');
  
  // Trim whitespace
  title = title.trim();
  
  return title || folderName;
}

/**
 * Parse player count from folder name.
 * Looks for patterns like "(7人开放)", "(4人)", "（7人）"
 * 
 * Returns default values (4, 8) if no pattern is found.
 */
export function parsePlayerCount(folderName: string): { min: number; max: number } {
  // Match patterns like (7人开放), (4人), （7人）
  const match = folderName.match(/[（(](\d+)人[开放）)]*[）)]/);
  
  if (match) {
    const count = parseInt(match[1], 10);
    return { min: count, max: count };
  }
  
  // Default values per Requirements 4.4
  return { min: 4, max: 8 };
}

/**
 * Infer the script category from folder name and contents.
 * 
 * Categories: horror, mystery, romance, comedy, thriller
 * Default: mystery (per Requirements 4.2)
 */
export function inferCategory(folderName: string): 'horror' | 'mystery' | 'romance' | 'comedy' | 'thriller' {
  const lowerName = folderName.toLowerCase();
  
  // Horror keywords
  if (/恐怖|惊悚|鬼|灵异|校规|诡异/.test(folderName)) {
    return 'horror';
  }
  
  // Romance keywords
  if (/爱情|情感|病娇|恋爱|浪漫/.test(folderName)) {
    return 'romance';
  }
  
  // Comedy keywords
  if (/喜剧|搞笑|欢乐/.test(folderName)) {
    return 'comedy';
  }
  
  // Thriller keywords
  if (/悬疑|推理|侦探|谋杀/.test(folderName)) {
    return 'thriller';
  }
  
  // Default to mystery
  return 'mystery';
}

/**
 * Infer the script difficulty from folder name.
 * 
 * Difficulties: easy, normal, hard
 * Default: normal (per Requirements 4.3)
 */
export function inferDifficulty(folderName: string): 'easy' | 'normal' | 'hard' {
  // Hard indicators
  if (/高难|困难|hard|复杂|烧脑/.test(folderName.toLowerCase())) {
    return 'hard';
  }
  
  // Easy indicators
  if (/简单|新手|入门|easy/.test(folderName.toLowerCase())) {
    return 'easy';
  }
  
  // Default to normal
  return 'normal';
}

/**
 * Extract all metadata from a folder name.
 */
export function extractMetadataFromFolderName(folderName: string): ScriptMetadata {
  const title = extractTitleFromFolderName(folderName);
  const { min, max } = parsePlayerCount(folderName);
  const category = inferCategory(folderName);
  const difficulty = inferDifficulty(folderName);
  
  return {
    title,
    minPlayers: min,
    maxPlayers: max,
    category,
    difficulty,
    description: '', // Will be generated by defaults module
  };
}
